name: gh_pages
description: Deploy files to gh-pages branch for Github Pages. Run from CLI or import into your project.
version: 0.1.0
repository: https://github.com/vaetas/gh_pages

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  gh_pages:

dependencies:
  args: ^2.0.0
  git: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.0
